### ISSUE TITLE
Demo code yields FunctionClauseError

### ISSUE THREAD

**Issue by michaelcaterisano** [CargoSense/absinthe_client#13]
@mcrumm I copied the usage code from the README into an iex session and got the following error

```
** (FunctionClauseError) no function clause matching in URI.parse/1

    The following arguments were given to URI.parse/1:

        # 1
        [graphql: "query { character(id: 1) { name } }"]

    Attempted function clauses (showing 2 out of 2):

        def parse(%URI{} = uri)
        def parse(string) when is_binary(string)

    (elixir 1.13.4) lib/uri.ex:765: URI.parse/1
    (req 0.3.6) lib/req.ex:423: Req.post/2
    (req 0.3.6) lib/req.ex:328: Req.post!/2
```

I ran:

```
Mix.install([
  {:absinthe_client, "~> 0.1.0"}
])

Req.new(base_url: "https://rickandmortyapi.com")
|> AbsintheClient.attach()
|> Req.post!(graphql: "query { character(id: 1) { name } }").body
```

Any idea what I'm doing wrong? I see that the output from `AbsintheClient.attach()` has a call to `URI.parse` with an empty string: 

```
%Req.Request{
  method: :get,
  url: URI.parse(""),
  headers: [],
  body: nil,
  options: %{base_url: "https://rickandmortyapi.com"},
  registered_options: #MapSet<[:unix_socket, :params, :path_params, :async,
   :cache_dir, :base_url, :raw, :connect_options, :json, :connect_params,
   :user_agent, :max_retries, :auth, :pool_timeout, :location_trusted, :finch,
   :plug, :output, :compress_body, :receive_timeout, :finch_request,
   :compressed, :max_redirects, :web_socket, :range, :cache, :extract, :form,
   :retry_log_level, :follow_redirects, :retry_delay, :graphql, :decode_body,
   :http_errors, :retry]>,
  halted: false,
  adapter: &Req.Steps.run_finch/1,
  request_steps: [
    graphql_run: #Function<0.34809413/1 in AbsintheClient."-fun.run/1-">,
    put_user_agent: &Req.Steps.put_user_agent/1,
    compressed: &Req.Steps.compressed/1,
    encode_body: &Req.Steps.encode_body/1,
    put_base_url: &Req.Steps.put_base_url/1,
    auth: &Req.Steps.auth/1,
    put_params: &Req.Steps.put_params/1,
    put_path_params: &Req.Steps.put_path_params/1,
    put_range: &Req.Steps.put_range/1,
    cache: &Req.Steps.cache/1,
    put_plug: &Req.Steps.put_plug/1,
    compress_body: &Req.Steps.compress_body/1
  ],
  response_steps: [
    retry: &Req.Steps.retry/1,
    follow_redirects: &Req.Steps.follow_redirects/1,
    decompress_body: &Req.Steps.decompress_body/1,
    decode_body: &Req.Steps.decode_body/1,
    handle_http_errors: &Req.Steps.handle_http_errors/1,
    output: &Req.Steps.output/1
  ],
  error_steps: [retry: &Req.Steps.retry/1],
  private: %{}
}
```

**Comment by michaelcaterisano** [comment]
Update: The code here works fine: https://elixirforum.com/t/absintheclient-graphql-client-with-subscriptions/50812

I think I'm just screwing up in iex :)
